application:
  envname: balaji
server:
  port: 7771
management:
  endpoints:
    web:
     exposure:
        include:
        - refresh
        - health
        - env
        - info
        - metrics
        - trace
        - beans
        - configprops
        - httptrace
        - loggers
        - metrics
        - shutdown
        
        
